language: generic
notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
sudo: required
dist: trusty
services:
  - docker
env:
  global:
    - ROS_PARALLEL_JOBS='-j8'
    - USE_DOCKER=true
    - EXTRA_DEB=gawk # until https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/85 is released
    -  TEST_PKGS="pddl_planner" # https://github.com/jsk-ros-pkg/jsk_planning/issues
  matrix:
    - ROS_DISTRO=hydro   USE_DEB=false
    - ROS_DISTRO=indigo  USE_DEB=true
    - ROS_DISTRO=jade    USE_DEB=true
    - ROS_DISTRO=kinetic USE_DEB=true
  allow_failures:
    - ROS_DISTRO=hydro   USE_DEB=true
before_script:
  - export ROS_PARALLEL_JOBS="-j2 -l2"
script: source .travis/travis.sh
